export const DIALOG_ON = 'DIALOG_ON'
export const DIALOG_OFF = 'DIALOG_OFF'


export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const LOADING_ON = 'LOADING_ON'
export const LOADING_OFF = 'LOADING_OFF'

export const LEFT_NAV_OPEN = 'LEFT_NAV_OPEN'
export const LEFT_NAV_CLOSE = 'LEFT_NAV_CLOSE'

export const WORKSPACE_PUT_CURRENT = 'WORKSPACE_PUT_CURRENT'

export const TODAY_PRAY_FOR_POST_POST_STUDENT_PRAY = 'TODAY_PRAY_FOR_POST_POST_STUDENT_PRAY'
export const TODAY_PRAY_FOR_POST_DELETE_STUDENT_PRAY = 'TODAY_PRAY_FOR_POST_DELETE_STUDENT_PRAY'
export const TODAY_PRAY_FOR_POST_POST_TODAY_PRAY = 'TODAY_PRAY_FOR_POST_POST_TODAY_PRAY'
export const TODAY_PRAY_FOR_POST_POST_ADS = 'TODAY_PRAY_FOR_POST_POST_ADS'
export const TODAY_PRAY_FOR_POST_INIT = 'TODAY_PRAY_FOR_POST_INIT'

export const DATEPICKER_OPEN = 'DATEPICKER_OPEN'
export const DATEPICKER_CLOSE = 'DATEPICKER_CLOSE'